// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjOOYn8kASgtYwEznDpYLlbVhwuO8W3YY',
    appId: '1:502633226086:web:0c7c7edd45e8cc90f2f2a7',
    messagingSenderId: '502633226086',
    projectId: 'virtual-stylist-26ea4',
    authDomain: 'virtual-stylist-26ea4.firebaseapp.com',
    storageBucket: 'virtual-stylist-26ea4.firebasestorage.app',
    measurementId: 'G-FV0FTRKLMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSkW-Cqsaseoolkzg2gi0S6d6j7q12Lww',
    appId: '1:502633226086:android:8c25dc40e373f580f2f2a7',
    messagingSenderId: '502633226086',
    projectId: 'virtual-stylist-26ea4',
    storageBucket: 'virtual-stylist-26ea4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV965KD9cJgtKfE3LlG5moDIwdVQNN_lg',
    appId: '1:502633226086:ios:2cd3680429c924d7f2f2a7',
    messagingSenderId: '502633226086',
    projectId: 'virtual-stylist-26ea4',
    storageBucket: 'virtual-stylist-26ea4.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV965KD9cJgtKfE3LlG5moDIwdVQNN_lg',
    appId: '1:502633226086:ios:2cd3680429c924d7f2f2a7',
    messagingSenderId: '502633226086',
    projectId: 'virtual-stylist-26ea4',
    storageBucket: 'virtual-stylist-26ea4.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjOOYn8kASgtYwEznDpYLlbVhwuO8W3YY',
    appId: '1:502633226086:web:0a22d39e1308cabcf2f2a7',
    messagingSenderId: '502633226086',
    projectId: 'virtual-stylist-26ea4',
    authDomain: 'virtual-stylist-26ea4.firebaseapp.com',
    storageBucket: 'virtual-stylist-26ea4.firebasestorage.app',
    measurementId: 'G-ETX8BCSS1Z',
  );
}
